spring:
  profiles:
    active: local

---
spring:
  profiles: local
  server.tomcat.uri-encoding: UTF-8
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  kakao:
    search-url: https://dapi.kakao.com/v2/search/book
    appKey: 8f2114ca4b84c6db0e4da2f6ca9ccd2a
---